#!/usr/bin/env python3
"""Render a portable static PDF from a completed Markdown audit or report.

Usage: python3 scripts/render_seo_report_pdf.py SEO-AUDIT.md --out output/pdf/SEO-AUDIT.pdf
Requires reportlab and a Unicode TrueType font supplied by --font, REPORT_FONT,
or a common system font path.
"""
from __future__ import annotations

import argparse
import html
import os
import re
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import BaseDocTemplate, CondPageBreak, Frame, PageBreak, PageTemplate, Paragraph, Spacer, Table, TableStyle


def find_font(explicit: str | None) -> Path:
    candidates = [explicit, os.getenv("REPORT_FONT"), r"C:\Windows\Fonts\arial.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"]
    for value in candidates:
        if value and Path(value).is_file():
            return Path(value)
    raise SystemExit("Unicode TTF font not found. Pass --font /path/to/font.ttf or set REPORT_FONT.")


def plain(markdown: str) -> str:
    links: list[tuple[str, str]] = []

    def preserve_link(match: re.Match[str]) -> str:
        label, target = match.group(1), match.group(2).strip().strip("<>")
        if not re.match(r"^https?://", target, flags=re.IGNORECASE):
            return label
        marker = f"\x00LINK{len(links)}\x00"
        links.append((label, target))
        return marker

    text = re.sub(r"!?\[([^]]*)\]\(([^)]+)\)", preserve_link, markdown)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = html.escape(text.strip())
    for index, (label, target) in enumerate(links):
        anchor = (
            f'<link href="{html.escape(target, quote=True)}" '
            f'color="#0F766E">{html.escape(label)}</link>'
        )
        text = text.replace(f"\x00LINK{index}\x00", anchor)
    return text


def footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#D8E1EB"))
    canvas.line(18 * mm, 13 * mm, 192 * mm, 13 * mm)
    canvas.setFont("ReportFont", 8)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.drawString(18 * mm, 8 * mm, "Audit report - generated by ru-seo-agent")
    canvas.drawRightString(192 * mm, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


def cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def is_divider(line: str) -> bool:
    return bool(re.match(r"^\|?\s*:?-{3,}", line))


def add_table(story, lines: list[str], body: ParagraphStyle, h3: ParagraphStyle) -> None:
    rows = [cells(line) for line in lines if not is_divider(line)]
    if len(rows) < 2:
        return
    headers, values = rows[0], rows[1:]
    if len(headers) <= 4:
        width = 174 * mm / len(headers)
        header_style = ParagraphStyle(
            "TableHeader", parent=body, textColor=colors.white, fontSize=8, leading=10
        )
        data = [[Paragraph(plain(value), header_style) for value in headers]]
        data.extend([[Paragraph(plain(value), body) for value in row] for row in values])
        table = Table(data, colWidths=[width] * len(headers), repeatRows=1, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F766E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, -1), "ReportFont"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("LEADING", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D8E1EB")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F8FA")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.extend([table, Spacer(1, 3 * mm)])
        return
    for row in values:
        title = row[0] if row else "Рекомендация"
        story.append(Paragraph(plain(title), h3))
        fields = [f"<b>{plain(header)}:</b> {plain(value)}" for header, value in zip(headers[1:], row[1:]) if value]
        story.append(Paragraph("<br/>".join(fields), body))
        story.append(Spacer(1, 2 * mm))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path, help="Completed Markdown report")
    parser.add_argument("--out", type=Path, required=True, help="Destination PDF path")
    parser.add_argument("--font", help="Unicode .ttf font path")
    args = parser.parse_args()
    source = args.input.read_text(encoding="utf-8")
    font = find_font(args.font)
    pdfmetrics.registerFont(TTFont("ReportFont", str(font)))
    styles = getSampleStyleSheet()
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontName="ReportFont", fontSize=9, leading=11.8, textColor=colors.HexColor("#243B53"), spaceAfter=3.2)
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontName="ReportFont", fontSize=21, leading=26, textColor=colors.HexColor("#102A43"), spaceBefore=5, spaceAfter=10, keepWithNext=1)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontName="ReportFont", fontSize=14, leading=18, textColor=colors.HexColor("#0F766E"), spaceBefore=10, spaceAfter=6, keepWithNext=1)
    h3 = ParagraphStyle("H3", parent=styles["Heading3"], fontName="ReportFont", fontSize=11, leading=14, textColor=colors.HexColor("#102A43"), spaceBefore=7, spaceAfter=4, keepWithNext=1)
    bullet = ParagraphStyle("Bullet", parent=body, leftIndent=5 * mm, firstLineIndent=-4 * mm)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    doc = BaseDocTemplate(str(args.out), pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=17 * mm, bottomMargin=19 * mm)
    doc.addPageTemplates(PageTemplate(id="report", frames=[Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="body")], onPage=footer))
    story = []
    in_code = False
    lines = source.splitlines()
    index = 0
    while index < len(lines):
        raw = lines[index]
        line = raw.rstrip()
        if line.startswith("|"):
            block = []
            while index < len(lines) and lines[index].rstrip().startswith("|"):
                block.append(lines[index].rstrip())
                index += 1
            add_table(story, block, body, h3)
            continue
        if line.startswith("```"):
            in_code = not in_code
            index += 1
            continue
        if in_code or not line:
            if not line:
                story.append(Spacer(1, 2 * mm))
            index += 1
            continue
        if line == "---":
            story.append(PageBreak())
        elif line.startswith("# "):
            story.append(CondPageBreak(45 * mm))
            story.append(Paragraph(plain(line[2:]), h1))
        elif line.startswith("## "):
            story.append(CondPageBreak(45 * mm))
            story.append(Paragraph(plain(line[3:]), h2))
        elif line.startswith("### "):
            story.append(CondPageBreak(50 * mm))
            story.append(Paragraph(plain(line[4:]), h3))
        elif re.match(r"^[-*] ", line):
            story.append(Paragraph("• " + plain(line[2:]), bullet))
        elif re.match(r"^\d+\. ", line):
            story.append(Paragraph(plain(line), bullet))
        else:
            story.append(Paragraph(plain(line), body))
        index += 1
    doc.build(story)
    print(args.out)


if __name__ == "__main__":
    main()
